import { Prisma } from '@prisma/client';

export type RagToolRecord = {
  id: string;
  name: string;
  slug: string;
  category: string;
  subcategory: string;
  company: string;
  website: string;
  domain: string;
  shortDescription: string;
  summary: string | null;
  features: Prisma.JsonValue;
  bestFor: Prisma.JsonValue;
  targetAudience: Prisma.JsonValue;
  tags: Prisma.JsonValue;
  aiType: Prisma.JsonValue;
  modalities: Prisma.JsonValue;
  modelProvider: Prisma.JsonValue;
  modelNames: Prisma.JsonValue;
  deploymentType: Prisma.JsonValue;
  platforms: Prisma.JsonValue;
  integrations: Prisma.JsonValue;
  pricingModel: string;
  startingPriceUsd: number | null;
  pricingNotes: string | null;
  freePlan: string;
  freeTrial: boolean;
  apiAvailable: boolean;
  openSource: boolean;
  teamCollaboration: boolean | null;
  security: Prisma.JsonValue;
  privacyNotes: string | null;
  status: string;
  launchYear: number | null;
  popularityScore: number | null;
  rating: number | null;
  reviewCount: number | null;
  sourceUrl: string;
  sourceType: string;
  searchText: string;
  updatedAt: Date;
};

export type RagRecommendation = {
  toolId: string;
  score: number;
  reason: string;
  matchedContext: string;
};
